apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-standalone
  namespace: argocd
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  sources:
  - name: git
    path: .
    repoURL: https://github.com/venkatasv/argocdsynctest.git
    targetRevision: HEAD
  - chart: redis
    helm:
      valueFiles:
      - $git:/infrastructure/redis-standalone/values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  destination:
    namespace: redis-cluster
    server: https://kubernetes.default.svc
  project: default
  sources:
  - name: git
    path: .
    repoURL: https://github.com/venkatasv/argocdsynctest.git
    targetRevision: HEAD
  - chart: redis-cluster
    helm:
      valueFiles:
      - $git:/infrastructure/redis-cluster/values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.x.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
spec:
  destination:
    namespace: postgresql
    server: https://kubernetes.default.svc
  project: default
  sources:
  - name: git
    path: .
    repoURL: https://github.com/venkatasv/argocdsynctest.git
    targetRevision: HEAD
  - chart: postgresql-ha
    helm:
      valueFiles:
      - $git:/infrastructure/postgresql-ha/values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.x.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  destination:
    namespace: postgresql
    server: https://kubernetes.default.svc
  project: default
  sources:
  - name: git
    path: .
    repoURL: https://github.com/venkatasv/argocdsynctest.git
    targetRevision: HEAD
  - chart: pgadmin4
    helm:
      valueFiles:
      - $git:/infrastructure/pgadmin/values.yaml
    repoURL: https://helm.runix.net
    targetRevision: 1.x.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
